// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Main from "./Main.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

document.body.append(Object.assign(document.createElement('div'),{id:"root"}));
;

var root = document.querySelector("#root");

if (root == null) {
  console.log("No root element found");
} else {
  ReactDom.render(React.createElement(Main.make, {}), root);
}

export {
  
}
/*  Not a pure module */
