// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Main = require("./Main.js");
var React = require("react");
var ReactDom = require("react-dom");
var FetchFilms = require("./FetchFilms.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Component = require("@loadable/component");

var data = Belt_Option.flatMap(Caml_option.undefined_to_opt(window.__APP_STATE__), FetchFilms.decodeFilms);

var root = document.querySelector("#root");

if (root == null) {
  console.log("No root element found");
} else {
  Component.loadableReady(function (param) {
        var tmp = {};
        if (data !== undefined) {
          tmp.data = Caml_option.valFromOption(data);
        }
        ReactDom.hydrate(React.createElement(Main.make, tmp), root);
        
      });
}

exports.data = data;
/* data Not a pure module */
