// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function Button(Props) {
  var label = Props.label;
  var onClick = Props.onClick;
  return React.createElement("button", {
              onClick: (function (_e) {
                  return Curry._1(onClick, undefined);
                })
            }, label);
}

var make = Button;

exports.make = make;
/* react Not a pure module */
