// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_json = require("rescript/lib/js/js_json.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function decodeFilms(data) {
  return Belt_Option.map(Js_json.decodeArray(data), (function (films) {
                return Belt_Array.map(films, Js_json.decodeObject);
              }));
}

function get(param) {
  return fetch("https://ghibliapi.herokuapp.com/films").then(function (prim) {
                return prim.json();
              }).then(function (films) {
              return Promise.resolve(decodeFilms(films));
            });
}

exports.decodeFilms = decodeFilms;
exports.get = get;
/* No side effect */
