// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Js_json from "bs-platform/lib/es6/js_json.js";
import * as Js_option from "bs-platform/lib/es6/js_option.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function GhibliList(Props) {
  var match = React.useState(function () {
        
      });
  var setList = match[1];
  var list = match[0];
  React.useEffect((function () {
          fetch("https://ghibliapi.herokuapp.com/films").then(function (prim) {
                    return prim.json();
                  }).then(function (films) {
                  return Promise.resolve(Js_json.decodeArray(films));
                }).then(function (list) {
                return Promise.resolve(Curry._1(setList, (function (param) {
                                  return Js_option.map((function (films) {
                                                return Belt_Array.map(films, Js_json.decodeObject);
                                              }), list);
                                })));
              });
          
        }), []);
  if (list !== undefined) {
    return React.createElement("ul", undefined, Belt_Array.map(list, (function (film) {
                      if (film === undefined) {
                        return null;
                      }
                      var film$1 = Caml_option.valFromOption(film);
                      return React.createElement("li", {
                                  key: JSON.stringify(film$1["id"])
                                }, JSON.stringify(film$1["title"]));
                    })));
  } else {
    return React.createElement("div", undefined, "No data yet");
  }
}

var make = GhibliList;

export {
  make ,
  
}
/* react Not a pure module */
