// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var FetchFilms = require("./FetchFilms.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function GhibliList(Props) {
  var films = Props.films;
  var match = React.useState(function () {
        return films;
      });
  var setList = match[1];
  var list = match[0];
  React.useEffect((function () {
          if (Belt_Option.isNone(films)) {
            FetchFilms.get(undefined).then(function (list) {
                  return Promise.resolve(Curry._1(setList, (function (param) {
                                    return list;
                                  })));
                });
          }
          
        }), []);
  if (list !== undefined) {
    return React.createElement("ul", undefined, Belt_Array.map(list, (function (film) {
                      if (film === undefined) {
                        return null;
                      }
                      var film$1 = Caml_option.valFromOption(film);
                      return React.createElement("li", {
                                  key: JSON.stringify(film$1["id"])
                                }, JSON.stringify(film$1["title"]));
                    })));
  } else {
    return React.createElement("div", undefined, "No data yet");
  }
}

var make = GhibliList;

exports.make = make;
/* react Not a pure module */
