// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var LazyComponent = require("./lazyComponent").default;

function makeComponent(prim) {
  return LazyComponent(prim);
}

exports.makeComponent = makeComponent;
/* ./lazyComponent Not a pure module */
