// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Button from "./Button.bs.js";
import * as GhibliList from "./GhibliList.bs.js";

function Main(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement("div", undefined, React.createElement(Button.make, {
                  label: "Hello World" + String(match[0]),
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (prev) {
                                    return prev + 1 | 0;
                                  }));
                    })
                }), React.createElement(GhibliList.make, {}));
}

var make = Main;

export {
  make ,
  
}
/* react Not a pure module */
